### PR TITLE
[release-4.18]: cephfs: log clone progress

### PR DESCRIPTION
**Pull request by Nikhil-Ladha**
This PR contains backport commits from devel for 4.18 branch.

### CODE REVIEW

**Comment by Madhu-1** [comment]
@Nikhil-Ladha can you please cherry-pick the commits? we only cherry-pick the commits when we want to backport to 4.18 branch

**Comment by Nikhil-Ladha** [comment]
> @Nikhil-Ladha can you please cherry-pick the commits? we only cherry-pick the commits when we want to backport to 4.18 branch

Sorry, didn't get you. I have cherry-picked the commits only, that were part of the other sync PR.

**Comment by Madhu-1** [comment]
> > @Nikhil-Ladha can you please cherry-pick the commits? we only cherry-pick the commits when we want to backport to 4.18 branch
> 
> Sorry, didn't get you. I have cherry-picked the commits only, that were part of the other sync PR.

can you please use `git cherry-pick -x` to preserve the history of cherry-pick?

**Comment by Nikhil-Ladha** [comment]
Ack, updated the PR to cherry-pick using the `-x` flag, does it looks good now?

**Pull request merged**
