### PR TITLE
BUG 2110013: rbd: remove checkHealthyPrimary check

### PR DESCRIPTION
**Pull request by Madhu-1**
After Failover of workloads to the secondary cluster when the primary cluster is down, RBD Image is not marked healthy, and VR resources are not promoted to the Primary, In VolumeReplication, the `CURRENT STATE` remains Unknown and doesn't change to Primary.

This happens because the primary cluster went down, and we have force promoted the image on the secondary cluster. and the image stays in up+stopping_replay or could be any other states. Currently assumption was that the image will always be `up+stopped`. But the image will be in `up+stopped` only for planned failover and it could be in any other state if its a forced failover. For this reason, removing checkHealthyPrimary from the PromoteVolume RPC call.

Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>
(cherry picked from commit 8c5563a9bcef229b6cfe54ae9fbfbbbed70089be)

### CODE REVIEW

**Review by Rakshith-R — APPROVED** [review]
/lgm

**Comment by humblec** [comment]
the linter is failing @Madhu-1

**Comment by Madhu-1** [comment]
> the linter is failing @Madhu-1

It's a known issue in 4.11

**Pull request merged**
