### PR TITLE
Bug 2233028: rebase: bump k8s.io dependencies to v0.26.7

### PR DESCRIPTION
**Pull request by karthik-us**
Bumping the k8s.io dependencies to v0.26.7. The main intention is to update the client-go library dependency for kube 1.27+, where aggregated discovery is enabled. With client-go lower than v0.26.4 in some cases it is possible that the discovery response comes with the malformed response with nil GVK leading to Crash Loop Back Off state.

Upstream kubernetes issue:
kubernetes/kubernetes#116603
(cherry picked from commit 68bf88a5f2d91081d819c43eedcb401c7a83eb91)

### CODE REVIEW

**Comment by nixpanic** [comment]
@karthik-us is this part of the release-14 and devel branches already?

**Comment by karthik-us** [comment]
> @karthik-us is this part of the release-14 and devel branches already?

Yes, both devel and 4.14 are using k8s.io versions 0.27+ and 4.13 is using the older problematic version.

**Review by nixpanic — COMMENTED** [review]
/lgtm

**Comment by nixpanic** [comment]
openshift/release#42649 has been merged, maybe it takes a little longer to get applied.... Need to retry the `/bugzilla refresh` a little later again.

**Pull request merged**
