### PR TITLE
Syncing latest changes from devel for ceph-csi

### PR DESCRIPTION
**Pull request by df-build-team**
PR containing the latest commits from devel branch

### CODE REVIEW

**Comment by Madhu-1** [comment]
@df-build-team am not sure how this PR is created, because the commits listed in this PR are still not present in the downstream devel branch yet, they are waiting to get merged https://github.com/red-hat-storage/ceph-csi/pull/305.

**Comment by nixpanic** [comment]
@Madhu-1 it seems that the commits in this PR are merged in the devel branch now?

Maybe @Nikhil-Ladha can explain the process how the backport to a release-4.x branch is done, and how/when the `sync_ds--devel` branch is created/updated.

**Comment by Madhu-1** [comment]
> @Madhu-1 it seems that the commits in this PR are merged in the devel branch now?
> 
> Maybe @Nikhil-Ladha can explain the process how the backport to a release-4.x branch is done, and how/when the `sync_ds--devel` branch is created/updated.

yes that true. it got merged later. unblocking this one for now.

**Comment by Nikhil-Ladha** [comment]
> @Madhu-1 it seems that the commits in this PR are merged in the devel branch now?
> 
> Maybe @Nikhil-Ladha can explain the process how the backport to a release-4.x branch is done, and how/when the `sync_ds--devel` branch is created/updated.

The sync to `release-4.x` branch happens when we have stable build for that release.
In this case, it is 4.17.

It syncs the commit from devel/main to the release-4.x branch.

**Comment by Madhu-1** [comment]
> @df-build-team am not sure how this PR is created, because the commits listed in this PR are still not present in the downstream devel branch yet, they are waiting to get merged #305.

@Nikhil-Ladha that was my expectation as well but that's not the case, even as the changes are not merged to devel branch got added to the release-4.17 branch as well.

**Comment by Nikhil-Ladha** [comment]
> > @df-build-team am not sure how this PR is created, because the commits listed in this PR are still not present in the downstream devel branch yet, they are waiting to get merged #305.
> 
> @Nikhil-Ladha that was my expectation as well but that's not the case, even as the changes are not merged to devel branch got added to the release-4.17 branch as well.

Oh ok, in that case it seems they are using upstream devel.
Will update the ref in the builds to use downstream devel instead, then we won't see this issue again.

**Pull request merged**
