### PR TITLE
Bug 2024870, 2046887: The SCC setting 'fsGroupChangePolicy: OnRootMismatch' is not honored when pods are scaled down / up

### PR DESCRIPTION
**Pull request by agarwal-mudit**

### CODE REVIEW

**Comment by Madhu-1** [comment]
@agarwal-mudit are we two different changes in one BUG?

**Comment by humblec** [comment]
@Madhu-1 one with ack, and other one dont have a bug yet.

**Comment by humblec** [comment]
Thanks @agarwal-mudit for the PR. :+1:

**Comment by nixpanic** [comment]
> @Madhu-1 one with ack, and other one dont have a bug yet.

Then this should not have been approved/merged! Only changes with a bug may get included in release-4.10, and sneaking in changes without a bug is not really a workflow we approve?

**Comment by agarwal-mudit** [comment]
> > @Madhu-1 one with ack, and other one dont have a bug yet.
> 
> Then this should not have been approved/merged! Only changes with a bug may get included in release-4.10, and sneaking in changes without a bug is not really a workflow we approve?

We still haven't switched to 4.10 branch in some components and are using main branch there. We should have, but we just had FF and this always happen because all of us merge the code on the last hours of the due FF date.
So, it is still fine to sync. From next week, we can be stricter once everyone else starts using 4.10 branch(es).

But anyway I have asked Humble to create a BZ, will link it to the PR.

**Pull request merged**
