### PR TITLE
Revert "rebase: bump github.com/go-jose/go-jose/v3 from 3.0.1 to 3.0.3"

### PR DESCRIPTION
**Pull request by Rakshith-R**
Reverts red-hat-storage/ceph-csi#270

This pr needs to be reverted for proper sync between DS devel and release-4.16 branch.

/cc @Madhu-1 @nixpanic

### CODE REVIEW

**Comment by nixpanic** [comment]
/hold

I don't think reverting is nice. Better rebase a manual sync PR on top of latest release-4.16?

**Comment by Rakshith-R** [comment]
> /hold
> 
> I don't think reverting is nice. Better rebase a manual sync PR on top of latest release-4.16?

I think its better to have proper sequence of commits that doesn't deviate much.
and resolving manual conflicts may complicate things further.

**Comment by nixpanic** [comment]
> I think its better to have proper sequence of commits that doesn't deviate much. 

This is normal with backports. Automation, or in this case _we_ are expected to be able to handle this without issues.

**Comment by nixpanic** [comment]
Addressed with #281.

**Pull request closed without merging**
