### PR TITLE
Syncing latest changes from devel for ceph-csi

### PR DESCRIPTION
**Pull request by df-build-team**
PR containing the latest commits from devel branch

### CODE REVIEW

**Comment by nixpanic** [comment]
These changes are not strictly required for the release-4.15 branch, but it is good to have them. It will probably make automatic rebasing in the future a little easier too.

/approve
/lgtm

**Comment by Madhu-1** [comment]
> These changes are not strictly required for the release-4.15 branch, but it is good to have them. It will probably make automatic rebasing in the future a little easier too.
> 
> /approve /lgtm

@nixpanic as this gets merged for the release branch without merging it to the devel branch won't it create a problem for rebasing or not having sync with downstream devel with release branches?

**Comment by nixpanic** [comment]
> @nixpanic as this gets merged for the release branch without merging it to the devel branch won't it create a problem for rebasing or not having sync with downstream devel with release branches?

Yes, that would be problematic. However the changes are only in downstream-only files like the `redhat/` directory. These can not come from the upstream project.

/approve

**Pull request merged**
