### PR TITLE
BUG 2303181: util: exclude empty label values for crushlocation map

### PR DESCRIPTION
**Pull request by iPraveenParihar**
# Describe what this PR does #

This commit resolves a bug where node labels with empty values
are processed for the `crush_location` mount option,
leading to invalid mount options and subsequent mount failures.

---

<details>
<summary>Show available bot commands</summary>

These commands are normally not required, but in case of issues, leave any of
the following bot commands in an otherwise empty comment in this PR:

* `/retest ci/centos/<job-name>`: retest the `<job-name>` after unrelated
  failure (please report the failure too!)

</details>

### CODE REVIEW

**Comment by iPraveenParihar** [comment]
@Madhu-1, do we want codespell to be fixed in this PR or a Separate?

**Comment by Madhu-1** [comment]
> @Madhu-1, do we want codespell to be fixed in this PR or a Separate?

@iPraveenParihar lets fix it in this PR itself, please add a commit for it as well.

**Pull request merged**
