### PR TITLE
BUG 2264002: rbd: log sitestatuses and description

### PR DESCRIPTION
**Pull request by yati1998**
This commit logs sitestatues and description in
GetVolumeReplicationInfo RPC call for better
debuging.

Fixes: #4430

Signed-off-by: Yati Padia <ypadia@redhat.com>
(cherry picked from commit cdc73a73519282abb13db3fbf25c77ed6110d46d)

### CODE REVIEW

**Comment by nixpanic** [comment]
@yati1998 @Madhu-1 can you please confirm that the changes are available in the devel and release-4.16 branch too?

See https://github.com/red-hat-storage/ceph-csi/tree/devel/redhat#backports for the process that we are required to follow:

1. change in upstream
2. backport/sync to downstream devel branch
3. backport to downstream release-4.16 branch
4. backport to downstream release-4.15 branch **<-- this PR**

If this process isn't followed, we may run into a regression if we forget to backport the changes to any of the other branches.

**Comment by Madhu-1** [comment]
@nixpanic yes changes are already in development as part of regular sync and 4.16 will be updated shortly as part of automation

**Pull request merged**
