### PR TITLE
Syncing latest changes from devel for ceph-csi

### PR DESCRIPTION
**Pull request by df-build-team**
PR containing the latest commits from devel branch

### CODE REVIEW

**Comment by nixpanic** [comment]
@Nikhil-Ladha this sync PR is not going very well. I am not sure what the cause could be, nor do I know how to correct it. Do you have a suggestion what to do about it?

**Comment by Nikhil-Ladha** [comment]
Seems like this has to be manually resolved, I don't think there is any other option.
Probably, a one time manual sync is needed and then the auto PR can do the syncing later on.

**Review by Madhu-1 — APPROVED** [review]

**Comment by Madhu-1** [comment]
> Seems like this has to be manually resolved, I don't think there is any other option. Probably, a one time manual sync is needed and then the auto PR can do the syncing later on.

@Nikhil-Ladha i did try to push rebase Pr for 4.17, it looks like i don't have any problem in local branch but its having merge conflict here any idea? 
cc @nixpanic

**Comment by Nikhil-Ladha** [comment]
I just tried this one and it shows conflict https://github.com/red-hat-storage/ceph-csi/pull/320

**Pull request closed without merging**
