### PR TITLE
BUG 2012143: rbd: check local image description for split-brain

### PR DESCRIPTION
**Pull request by Madhu-1**
In some corner cases like `re-player shutdown` the local image will not be in an error state. It would
be also worth considering the `description` field to make sure about split-brain.

Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>
(cherry picked from commit 0d51f6d833f749214377c8c9616cd68760c7de58)

### CODE REVIEW

**Review by agarwal-mudit — APPROVED** [review]
/lgtm

**Comment by nixpanic** [comment]
This was backported and merged before the changes are in the `red-hat-storage/ceph-csi:devel` branch :disappointed:

**Comment by agarwal-mudit** [comment]
> This was backported and merged before the changes are in the `red-hat-storage/ceph-csi:devel` branch disappointed

Sorry, my mistake. Was in a hurry for dev freeze :(

**Comment by Madhu-1** [comment]
> This was backported and merged before the changes are in the `red-hat-storage/ceph-csi:devel` branch disappointed

@nixpanic one thing I don't understand is backporting the PR to devel branch what is the advantage of having it? for the next release, AFAIK we always sync the upstream devel with downstream devel and create a new release-4.x branch.

**Comment by nixpanic** [comment]
> > This was backported and merged before the changes are in the `red-hat-storage/ceph-csi:devel` branch disappointed
> 
> @nixpanic one thing I don't understand is backporting the PR to devel branch what is the advantage of having it? for the next release, AFAIK we always sync the upstream devel with downstream devel and create a new release-4.x branch.

We should never be in a position where regressions are possible. The devel branch is expected to have all the changes (from upstream, but also downstream-only) before they land in branches that are used for product builds. This is not only relevant for the devel branch, but also for changes that need to be done in release-4.8. Changes for release-4.8 are required to also be included in the devel branch, and release-4.9 before getting backported to release-4.8.

There is work being done to get builds from all projects devel/main/.. branches and create a "ODF next alpha" product version. Such a version may not have missing changes that are only part of release-branches.

**Comment by Madhu-1** [comment]
sounds good.  sorry for missing the backport to devel here is the PR https://github.com/red-hat-storage/ceph-csi/pull/38

**Pull request merged**
