### PR TITLE
Syncing latest changes from devel for ceph-csi

### PR DESCRIPTION
**Pull request by df-build-team**
PR containing the latest commits from devel branch

### CODE REVIEW

**Comment by Nikhil-Ladha** [comment]
@Madhu-1 can we please get this PR merged as well?

**Comment by Nikhil-Ladha** [comment]
I see that some of the commits are merged in the other PR :/

**Comment by Madhu-1** [comment]
> I see that some of the commits are merged in the other PR :/

i thought we stopped syncing 4.18 branch and only do cherry-pick.

**Comment by Nikhil-Ladha** [comment]
> > I see that some of the commits are merged in the other PR :/
> 
> i thought we stopped syncing 4.18 branch and only do cherry-pick.

Yeah, this PR was opened on Friday

**Comment by Madhu-1** [comment]
@Nikhil-Ladha it looks like the bot required valid-bug label, do we need to add it manually?

**Comment by Nikhil-Ladha** [comment]
> @Nikhil-Ladha it looks like the bot required valid-bug label, do we need to add it manually?

I can add that manually, but what about the duplicate commits?

**Comment by Madhu-1** [comment]
> I see that some of the commits are merged in the other PR :/

>i thought we stopped syncing 4.18 branch and only do cherry-pick.

> Yeah, this PR was opened on Friday

As i was on PTO, this got slipped.


or close this and cherry-pick only required commit? like clone progress one?

**Comment by Nikhil-Ladha** [comment]
No worries, seems like that's the best option i.e, to cherry-pick the commits.
We can merge that without a bug for now, and have the labels added manually.

**Pull request closed without merging**
