### PR TITLE
Sync red-hat-storage/ceph-csi:release-4.9 with ceph/ceph-csi:devel

### PR DESCRIPTION
**Pull request by agarwal-mudit**

### CODE REVIEW

**Comment by Madhu-1** [comment]
@agarwal-mudit as we have release-3.4 branch which is base for 4.9 can we sync from it?

**Comment by agarwal-mudit** [comment]
> @agarwal-mudit as we have release-3.4 branch which is base for 4.9 can we sync from it?
We are still not in feature freeze so devel is fine for now. 
Once we are in feature freeze, we should stop resync and should merge the individual patches.

If there is some specific reason to merge from 3.4 then I can close this and open one for that

**Comment by Madhu-1** [comment]
I was thinking as we have base branch we can make use of it and stop using devel branch

**Comment by agarwal-mudit** [comment]
> I was thinking as we have base branch we can make use of it and stop using devel branch

Lets do it after feature freeze

**Review by nixpanic — APPROVED** [review]

**Pull request merged**
